### ISSUE TITLE
Only use vetted actions

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#11]
Right now we use actions from all over the place. For security, we want to only use actions from vetted sources.

https://docs.google.com/document/d/10QONpg2mO_-psjhpHYLRCgPdT9HpmH788Ec-YvlRi4I/edit?usp=sharing

### Todo

- [x] Find all actions we use
- [ ] Fork and audit actions from randos
- [ ] Configure GitHub to only allow actions from trusted orgs.
