### ISSUE TITLE
Add template validation bot

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#8]
Auto close issues and PRs not adhering to the templates

Example: https://github.com/seferov/pr-lint-action

### Todo

- [x] better log message than full echo template
- [x] auto-close on fail, with comment
- [x] write real comment
- [x] deploy to `onpremise`
- [x] close hole: https://github.com/getsentry/onpremise/pull/822
- [x] look into `\r` bug: https://github.com/getsentry/.github/issues/8#issuecomment-761062699
- [x] relax match constraint: https://github.com/getsentry/.github/issues/15
- [x] harden against additional ISSUE_TEMPLATE situations: https://github.com/getsentry/.github/issues/26
- [x] ~~make log download more robust (seeing [off-by-ones](https://github.com/getsentry/.github-chadwhitacre/runs/1787332012?check_suite_focus=true), probably race condition?)~~ &rarr; https://github.com/getsentry/.github/issues/30
- [x] ~~probably convert to an action~~
- [x] deploy to `onpremise`
- [x] deploy to `sentry-docs`
- [x] deploy to `sentry`

**Comment by chadwhitacre** [comment]
I want to review our templates as part of this.

I also want to consider automation that nudges people to reveal more info vs. hard-closing right off the bat. There was this early AI bot called [Dr. Sbaitso](https://en.wikipedia.org/wiki/Dr._Sbaitso) that would basically just rubber duck. "How do you feel? Tell me more about your problems." That kind of thing. I find this approach can be an effective way to turn [a bad first post into an interesting conversation](https://github.com/getsentry/onpremise/issues/793). "What version are you running? What have you done to debug? What hypotheses do you have?" I'd like to explore automating _that_ vs. automating "No soup for you!"

**Comment by chadwhitacre** [comment]
Like maybe having a bot watch for the `Needs More Info` label and following up with a comment?

**Comment by chadwhitacre** [comment]
Fire on [`issues`](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issues), need to compare against all possible template types. Want to use single source of truth for template definition. Easy heuristic would be to compare headings in description and template, roughly:

```
diff -rub $(grep '^#' actual) $(grep '^#' actual)
```

**Comment by chadwhitacre** [comment]
No-op GHA that fires on issue open:

https://github.com/chadwhitacre/chadwhitacre-testing-nothing-to-see-here/actions/runs/481292243

Takes 18 seconds to run. Seems like a lot to run on every single issue open. 🐭

**Comment by chadwhitacre** [comment]
actual: https://github.com/chadwhitacre/chadwhitacre-testing-nothing-to-see-here/runs/1691291348?check_suite_focus=true#step:2:6

next step is to pull expected ... clone repo and read `.github/ISSUE_TEMPLATE`? do I already have a repo clone?

**Comment by chadwhitacre** [comment]
MVP: https://github.com/chadwhitacre/chadwhitacre-testing-nothing-to-see-here/issues/20#issuecomment-759751070

**Comment by chadwhitacre** [comment]
Choking on `\r`?

https://github.com/getsentry/onpremise/runs/1708876463?check_suite_focus=true

```
2021-01-15T13:48:33.7472458Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: line 54: $'\r': command not found
2021-01-15T13:48:33.7481004Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: line 55: TypeError: command not found
2021-01-15T13:48:33.7487873Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: command substitution: line 56: syntax error near unexpected token `('
2021-01-15T13:48:33.7490627Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: command substitution: line 56: `r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
2021-01-15T13:48:33.7492405Z '
2021-01-15T13:48:33.7504446Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: line 54: $'\r': command not found
2021-01-15T13:48:33.7513927Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: line 55: TypeError: command not found
2021-01-15T13:48:33.7520816Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: command substitution: line 56: syntax error near unexpected token `('
2021-01-15T13:48:33.7523228Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: command substitution: line 56: `r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
2021-01-15T13:48:33.7524920Z '
2021-01-15T13:48:33.7534951Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: line 54: $'\r': command not found
2021-01-15T13:48:33.7542001Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: line 55: TypeError: command not found
2021-01-15T13:48:33.7546351Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: command substitution: line 56: syntax error near unexpected token `('
2021-01-15T13:48:33.7548485Z /home/runner/work/_temp/b836d143-90e1-4150-bbcb-6cc9d82121f5.sh: command substitution: line 56: `r.takeRecords is not a function. (In 'r.takeRecords()', 'r.takeRecords' is undefined)
2021-01-15T13:48:33.7549707Z '
20
```

**Comment by chadwhitacre** [comment]
> Choking on `\r`?

Nope. Dutifully performing command substitution. This is another demonstration of the vuln class in https://github.com/getsentry/onpremise/pull/822, and a confirmation that the first approach to fixing it was indeed insufficient:

```
$ BAR="`head -n3 /etc/passwd`"
$ echo "$BAR"
##
# User Database
# 
$
```

**Comment by chadwhitacre** [comment]
Done and deployed! 💃 

https://github.com/getsentry/onpremise/pull/845
https://github.com/getsentry/sentry-docs/pull/2988
https://github.com/getsentry/sentry/pull/23493
